services:
  sia-server:
    build: .
    image: sia-server:latest
    container_name: sia-server
    environment:
      - TZ=Europe/London 
    ports:
      - "10000:10000"
      - "10001:10001"
    restart: unless-stopped
    volumes:
      - ./sia-server.conf:/config/sia-server.conf:ro
      - ./logs:/logs 
