services:
  sia-server:
    build: .
    container_name: sia-server

    network_mode: host

    restart: unless-stopped

    volumes:
      - ./sia-server.conf:/config/sia-server.conf:ro
      - ./logs:/logs  # optional, only needed if LOG_TO = File
